Simplify (#1)
* see if build even still works

* Migrate to v2 of actions for R setup and Rmd rendering

* Include reference to DaveParr.Info

* Add Rprofile, gitignore, and settings files for renv
Remove code for fetching dev.to blogs
Modify grpah to be ordered by count

* Include forcats dependency

* Pin r version

* Formatting

* Add libcurl installation step and update blog link

* Re-build Rmarkdown files

* Include graph update job

* Update the graph

* Re-build Rmarkdown files

---------

Co-authored-by: DaveParr <DaveParr@users.noreply.github.com>
Co-authored-by: GitHub Actions <actions@github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,34 +1,39 @@
-name: Generate new graph
-
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: [ main ]
-  schedule:
-    - cron:  '0 1 * * *'
-      
+    paths: ['**.Rmd']
+
+name: render-rmarkdown
+
 jobs:
-  build:
-    runs-on: macos-latest
+  render-rmarkdown:
+    runs-on: ubuntu-latest
     env:
-      DEVTO: ${{ secrets.DEVTO }}
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - uses: actions/checkout@v1
-      - uses: r-lib/actions/setup-r@v1
-      - uses: r-lib/actions/setup-pandoc@v1
-      - name: Install Dependencies
-        run: |-
-          Rscript -e "install.packages('remotes')"
-          Rscript -e "install.packages('gh')"
-          Rscript -e "install.packages('tibble')"
-          Rscript -e "install.packages('tidyr')"
-          Rscript -e "install.packages('dplyr')"
-          Rscript -e "install.packages('ggplot2')"
-          Rscript -e "install.packages('stringr')"
-          Rscript -e "remotes::install_github('DaveParr/dev.to.ol')"
+      - name: Install libcurl
+        run: >
+          sudo apt-get update && sudo apt-get install --yes
+          libcurl4-openssl-dev
+
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - uses: r-lib/actions/setup-r@v2
+        with:
+            r-version: '4.1.2'
+
+      - uses: r-lib/actions/setup-renv@v2
+
       - name: Run repos
         run: |-
           Rscript -e "source('repos.R')"
+          
       - name: Commit updated graph
         run: |
           git config --local user.email "actions@github.com"
@@ -36,14 +41,13 @@ jobs:
           git add graph.png
           git commit -m "Update the graph" -a || echo "No changes to commit"
           git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
-      - name: Install rmarkdown
-        run: Rscript -e 'install.packages("rmarkdown")'
-      - name: Render README
-        run: Rscript -e 'rmarkdown::render("README.Rmd")'
-      - name: Commit updated README
+
+      - name: Render Rmarkdown files and Commit Results
         run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
           git push origin || echo "No changes to commit"
           
